included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - identifier_name

shorthand_operator: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

# configurable rules can be customized from this configuration file
line_length: 200
